(()=>{'use strict';
const SB='https://lfyxjbcsrsmbaflhbtbx.supabase.co',KEY='sb_publishable_VrglfWR4mfvAcrm1MLZY3Q_XH6L5st1';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'],BIG=['12:00','12:35','13:10','13:45','14:20','14:55','15:30','16:00'];
let people=[],$=x=>document.getElementById(x),M=x=>{let[a,b]=String(x).split(':').map(Number);return a*60+b},F=x=>String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');
async function api(path,o={}){o.headers={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(o.headers||{})};let r=await fetch(SB+'/rest/v1/'+path,o),t=await r.text();if(!r.ok)throw Error(t||r.status);return t.trim()?JSON.parse(t):null}
function wk(){return DAYS.map((_,i)=>({work:i<5,start:'08:00',end:'18:00'}))} function today(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('date').value=d.toISOString().slice(0,10)} function dow(){return(new Date($('date').value+'T12:00')).getDay()||7} function ro(p){return p.week[dow()-1]} function hrs(w){return(M(w.end)-M(w.start))/60} function rights(w){return hrs(w)>6?['mini1','big','mini2']:hrs(w)>4?['mini1','mini2']:[]} function active(){return people.filter(p=>p.active&&p.type==='KCC'&&ro(p)?.work)}
async function load(){let rows=await api('kcc_work_profiles?select=*&order=name'),ids=(rows||[]).map(x=>x.id),ss=ids.length?await api('kcc_work_schedule?select=*&profile_id=in.('+ids.join(',')+')'):[];people=(rows||[]).map(r=>{let p={id:r.id,name:r.name,type:r.type||'KCC',active:r.active!==false,pref:r.big_break_preference?String(r.big_break_preference).slice(0,5):'',week:wk(),open:false};(ss||[]).filter(s=>s.profile_id===r.id).forEach(s=>p.week[s.weekday-1]={work:s.working,start:s.start_time?String(s.start_time).slice(0,5):'08:00',end:s.end_time?String(s.end_time).slice(0,5):'18:00'});return p});render();generate()}
function can(plan,t,kind,ignorePref=false){let s=M(t),e=s+(kind==='big'?30:10);for(let x=s;x<e;x+=5){let bs=plan.filter(b=>(ignorePref||!b.pref)&&M(b.t)<=x&&x<M(b.t)+(b.kind==='big'?30:10));if(kind==='big'&&bs.filter(b=>b.kind==='big').length>=2)return false;if(kind!=='big'&&bs.length>=3)return false}return true}
function bigSlots(w){return BIG.filter(t=>M(t)>=Math.max(720,M(w.start))&&M(t)+30<=M(w.end))}
function pickBig(plan,p,w){let v=bigSlots(w);if(!v.length)return null;if(p.pref&&v.includes(p.pref))return{t:p.pref,pref:true,exception:false};let free=v.filter(t=>can(plan,t,'big'));if(free.length)return{t:free[0],pref:false,exception:false};let ex=v.find(t=>{let s=M(t);return plan.filter(b=>!b.pref&&b.kind==='big'&&M(b.t)<=s&&s<M(b.t)+30).length<3});return ex?{t:ex,pref:false,exception:true}:null}
function miniCandidates(w,k,target){let lo=k==='mini1'?(M(w.start)<=510?600:720):720,hi=k==='mini1'?(M(w.start)<=510?720:840):1020,a=[];for(let x=lo;x<=hi&&x+10<=M(w.end);x+=5)a.push(F(x));return a.sort((a,b)=>Math.abs(M(a)-target)-Math.abs(M(b)-target))}
function generate(){let a=active().sort((x,y)=>M(ro(x).start)-M(ro(y).start)||x.name.localeCompare(y.name)),plan=[];
// Grote pauze eerst: vroege starters eerst; voorkeuren worden als harde wensen ingepland en zijn vrijgesteld.
a.filter(p=>p.pref).forEach(p=>{let c=pickBig(plan,p,ro(p));if(c)plan.push({p,kind:'big',t:c.t,pref:true,exception:false})});
a.filter(p=>!p.pref).forEach(p=>{let c=pickBig(plan,p,ro(p));if(c)plan.push({p,kind:'big',t:c.t,pref:false,exception:c.exception})});
// Mini's daarna. Max 2 mini's + 1 grote is toegestaan; max 2 grote normaal.
a.forEach(p=>{let w=ro(p),r=rights(w),b=plan.find(x=>x.p===p&&x.kind==='big');if(r.includes('mini1')){let target=b?M(b.t)-120:M(w.start)+120,t=miniCandidates(w,'mini1',target).find(z=>can(plan,z,'mini'));if(t)plan.push({p,kind:'mini1',t,pref:false})}if(r.includes('mini2')){let f=plan.find(x=>x.p===p&&x.kind==='mini1'),target=b?M(b.t)+120:f?M(f.t)+120:M(w.start)+240,t=miniCandidates(w,'mini2',target).find(z=>can(plan,z,'mini'));if(t)plan.push({p,kind:'mini2',t,pref:false})}});
plan.sort((a,b)=>M(a.t)-M(b.t)||a.kind.localeCompare(b.kind));renderPlan(plan);score(plan,a)}
function score(plan,a){let hard=0,missing=0;for(let t=720;t<=1020;t+=5){let bs=plan.filter(b=>!b.pref&&M(b.t)<=t&&t<M(b.t)+(b.kind==='big'?30:10)),big=bs.filter(b=>b.kind==='big');if(big.length>2||bs.length>3)hard++}a.forEach(p=>rights(ro(p)).forEach(k=>{if(!plan.some(b=>b.p===p&&b.kind===k))missing++}));let exc=plan.filter(b=>b.exception&&!b.pref).length,warnings=hard+exc+missing;$('statWarnings').textContent=warnings;$('statBreaks').textContent=plan.length;$('score').textContent=Math.max(0,100-Math.min(100,hard*1.5+exc*2+missing*3)).toFixed(0)+'%';$('alerts').innerHTML=warnings?`<div class=alert>⚠️ ${warnings} aandachtspunt(en). ${missing?missing+' pauze(s) konden niet binnen de normale regels worden geplaatst. ':''}${exc?exc+' grote pauze(s) gebruiken een uitzonderingsplek. ':''}Voorkeuren zijn volledig vrijgesteld van de score.</div>`:'<div class=alert>✓ Geen aandachtspunten.</div>'}
function renderPlan(plan){let s=$('schedule');s.innerHTML='';let by={};plan.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>M(a)-M(b)).forEach(t=>s.insertAdjacentHTML('beforeend',`<div class=slot><time>${t}</time><div class=cards>${by[t].map(b=>`<div class="breakcard ${b.kind==='big'?'bigcard':''} ${b.exception?'warningcard':''}"><b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'}${b.exception?' ⚠️':''}</div>`).join('')}</div></div>`))}
function render(){let b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>{let opts='<option value="">Geen voorkeur</option>'+BIG.map(x=>`<option value="${x}" ${p.pref===x?'selected':''}>${x}</option>`).join('');b.insertAdjacentHTML('beforeend',`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.pref||'Geen voorkeur'}</td><td>${p.active?'✓':'—'}</td><td><button class=profileBtn data-i=${i}>${p.open?'Sluiten':'Profiel'}</button></td></tr>`);if(p.open)b.insertAdjacentHTML('beforeend',`<tr><td colspan=5><div class=profileBox><b>Werkprofiel: ${p.name}</b></div></td></tr>`)});b.querySelectorAll('.profileBtn').forEach(x=>x.onclick=()=>{people[x.dataset.i].open=!people[x.dataset.i].open;render()})}
async function init(){today();$('generate').onclick=generate;await load()}init()})();