(()=>{
'use strict';
const KEY='kcc_profiles_v3';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'];
const BIG=['12:00','12:35','13:10','13:45','14:20','14:55','15:30','16:00'];
const NAMES=['Harman Satpal','Peggy Peerkhan','Nella Faneyte','Hester van den Wittenboer','Marie-Jean Djaoen','Simone de Groot','Anoushka Ramcharan','David van Onselen','Alicia Rodriques','Chelsea Hibbert','Turgay Can','Melvin Cairo','Magdalena de Windt','Gernarda Raap','Hriteesha Poeran','Sjaiesta Billar','Tamara Kuntkes','Mathijs Van der Wouden','Dharendenie Autar','Fara Wirjopawiro Durga','Cherrelle Goudmijn','Asli Semen','Cindy Wooter','Smahane Almakroudi','Savienne Wawoe','Dries Mouna','Mandy Spaans','Shanaaz Nasrullah','Safae Ghay','Naima Saghrioui','Sara Winter','Jaylisa Emanuelson','Reshma Ramroop','Sharita Jaipal'];
let people=[];
const $=id=>document.getElementById(id), m=s=>{let [h,mi]=s.split(':').map(Number);return h*60+mi}, f=x=>String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');
function week(){return DAYS.map((_,i)=>({work:i<5,start:'08:00',end:'18:00'}))}
function profile(name){return {name,type:'KCC',active:true,pref:'',week:week(),open:false}}
function today(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('date').value=d.toISOString().slice(0,10)}
function day(){let v=$('date').value;return v?new Date(v+'T12:00:00').getDay()||7:((new Date().getDay()||7))}
function roster(p){let w=p.week[(day()+6)%7];return w&&w.work?w:null}
function hours(w){return(m(w.end)-m(w.start))/60}
function rights(w){let h=hours(w);return h>6?['mini1','big','mini2']:h>4?['mini1','mini2']:[]}
function active(){return people.filter(p=>p.active&&p.type==='KCC'&&roster(p))}
function save(){localStorage.setItem(KEY,JSON.stringify(people))}
function reset(){localStorage.removeItem('kcc_profiles_v2');localStorage.removeItem('kcc_profiles_v3');people=NAMES.map(profile);save();render();generate()}
function load(){try{people=JSON.parse(localStorage.getItem(KEY))||[]}catch(e){people=[]}if(!people.length){people=NAMES.map(profile);save()}}
function render(){let b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>{let opts='<option value="">Geen voorkeur</option>'+BIG.map(x=>`<option value="${x}" ${p.pref===x?'selected':''}>${x}</option>`).join('');b.insertAdjacentHTML('beforeend',`<tr><td><input class="name" data-i="${i}" value="${p.name}"></td><td><select class="type" data-i="${i}"><option ${p.type==='KCC'?'selected':''}>KCC</option><option ${p.type==='Webcare'?'selected':''}>Webcare</option><option ${p.type==='Coördinator'?'selected':''}>Coördinator</option></select></td><td><select class="pref" data-i="${i}">${opts}</select></td><td><input type="checkbox" class="active" data-i="${i}" ${p.active?'checked':''}></td><td><button class="secondary profileBtn" data-i="${i}">${p.open?'Sluiten':'Profiel'}</button></td><td><button class="secondary remove" data-i="${i}">Verwijder</button></td></tr>`);if(p.open){b.insertAdjacentHTML('beforeend',`<tr class="profileRow"><td colspan="6"><div class="profileBox"><div class="profileTitle"><b>Werkprofiel: ${p.name}</b><span>Stel per dag werktijden in.</span></div><div class="weekGrid">${DAYS.map((d,di)=>{let w=p.week[di];return `<div class="dayCard"><b>${d}</b><label><input type="checkbox" class="dayWork" data-i="${i}" data-d="${di}" ${w.work?'checked':''}> Werkt</label><input type="time" class="dayStart" data-i="${i}" data-d="${di}" value="${w.start}" ${w.work?'':'disabled'}><span>tot</span><input type="time" class="dayEnd" data-i="${i}" data-d="${di}" value="${w.end}" ${w.work?'':'disabled'}></div>`}).join('')}</div></div></td></tr>`)}});b.querySelectorAll('.profileBtn').forEach(x=>x.onclick=()=>{people[+x.dataset.i].open=!people[+x.dataset.i].open;render()});b.querySelectorAll('.remove').forEach(x=>x.onclick=()=>{people.splice(+x.dataset.i,1);save();render();generate()});b.querySelectorAll('input,select').forEach(x=>x.onchange=()=>{let i=+x.dataset.i,d=x.dataset.d,p=people[i];if(x.classList.contains('name'))p.name=x.value;if(x.classList.contains('type'))p.type=x.value;if(x.classList.contains('pref'))p.pref=x.value;if(x.classList.contains('active'))p.active=x.checked;if(d!==undefined){d=+d;if(x.classList.contains('dayWork'))p.week[d].work=x.checked;if(x.classList.contains('dayStart'))p.week[d].start=x.value;if(x.classList.contains('dayEnd'))p.week[d].end=x.value}save();render();generate()});$('statPeople').textContent=active().length}
function overlap(plan,t,kind){let len=kind==='big'?30:10;for(let x=m(t);x<m(t)+len;x+=5){let big=0,total=0;plan.forEach(b=>{let e=m(b.t)+(b.kind==='big'?30:10);if(x>=m(b.t)&&x<e){total++;if(b.kind==='big')big++}});if(kind==='big'&&big>=2)return false;if(kind!=='big'&&total>=3)return false}return true}
function chooseBig(plan,p,w){let valid=BIG.filter(t=>m(t)>=Math.max(720,m(w.start)+60)&&m(t)+30<=m(w.end));if(p.pref&&valid.includes(p.pref))return p.pref;if(p.pref)valid.sort((a,b)=>Math.abs(m(a)-m(p.pref))-Math.abs(m(b)-m(p.pref)));else valid.sort((a,b)=>m(a)-m(b));return valid.find(t=>overlap(plan,t,'big'))||valid[0]}
function miniOptions(w,kind,target){let lo=kind==='mini1'?(w.start<='08:30'?600:720):720,hi=kind==='mini1'?(w.start<='08:30'?720:840):1020,a=[];for(let x=lo;x<=hi;x+=5)if(x+10<=m(w.end))a.push(f(x));return a.sort((a,b)=>Math.abs(m(a)-target)-Math.abs(m(b)-target))}
function generate(){let a=active(),plan=[];a.sort((x,y)=>(x.pref?m(x.pref):9999)-(y.pref?m(y.pref):9999));a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('big')){let t=chooseBig(plan,p,w);if(t)plan.push({p,kind:'big',t,pref:!!p.pref})}});a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('mini1')){let b=plan.find(x=>x.p===p&&x.kind==='big'),o=miniOptions(w,'mini1',b?m(b.t)-120:m(w.start)+120),t=o.find(z=>overlap(plan,z,'mini1'))||o[0];if(t)plan.push({p,kind:'mini1',t,pref:false})}});a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('mini2')){let b=plan.find(x=>x.p===p&&x.kind==='big'),f1=plan.find(x=>x.p===p&&x.kind==='mini1'),target=b?m(b.t)+120:f1?m(f1.t)+120:m(w.start)+240,o=miniOptions(w,'mini2',target),t=o.find(z=>overlap(plan,z,'mini2'))||o[0];if(t)plan.push({p,kind:'mini2',t,pref:false})}});renderPlan(plan);score(plan)}
function score(plan){let hard=0;for(let t=720;t<=990;t+=5){let bs=plan.filter(b=>m(b.t)<=t&&t<m(b.t)+(b.kind==='big'?30:10));let big=bs.filter(b=>b.kind==='big');if(big.some(b=>b.pref))continue;if(big.length>2||bs.length>3)hard++}$('score').textContent=(hard?Math.max(0,100-hard*5):100)+'%';$('statWarnings').textContent=hard;$('statBreaks').textContent=plan.length;$('alerts').innerHTML=hard?`<div class="alert">⚠️ ${hard} bezettingsaandachtspunt(en). Persoonlijke voorkeuren zijn vrijgesteld.</div>`:'<div class="alert">✓ Geen bezettingsaandachtspunten. Voorkeuren overrulen zachte regels.</div>'}
function renderPlan(plan){let s=$('schedule');s.innerHTML='';let by={};plan.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>m(a)-m(b)).forEach(t=>{s.insertAdjacentHTML('beforeend',`<div class="slot"><time>${t}</time><div class="cards">${by[t].map(b=>`<div class="breakcard ${b.kind==='big'?'bigcard':''}"><b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'}<input type="time" value="${b.t}"></div>`).join('')}</div></div>`)});s.querySelectorAll('input').forEach((x,i)=>x.onchange=()=>{let b=plan[i];if(b){b.t=x.value;renderPlan(plan);score(plan)}})}
function init(){today();load();render();generate();$('date').onchange=generate;$('generate').onclick=generate;$('loadDemo').onclick=reset;$('addPerson').onclick=()=>{let p=profile('Nieuwe collega');p.open=true;people.push(p);save();render();generate()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();