(()=>{
'use strict';
const SB='https://lfyxjbcsrsmbaflhbtbx.supabase.co';
const KEY='sb_publishable_VrglfWR4mfvAcrm1MLZY3Q_XH6L5st1';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'];
const BIG=['12:00','12:35','13:10','13:45','14:20','14:55','15:30','16:00'];
const NAMES=['Harman Satpal','Peggy Peerkhan','Nella Faneyte','Hester van den Wittenboer','Marie-Jean Djaoen','Simone de Groot','Anoushka Ramcharan','David van Onselen','Alicia Rodriques','Chelsea Hibbert','Turgay Can','Melvin Cairo','Magdalena de Windt','Gernarda Raap','Hriteesha Poeran','Sjaiesta Billar','Tamara Kuntkes','Mathijs Van der Wouden','Dharendenie Autar','Fara Wirjopawiro Durga','Cherrelle Goudmijn','Asli Semen','Cindy Wooter','Smahane Almakroudi','Savienne Wawoe','Dries Mouna','Mandy Spaans','Shanaaz Nasrullah','Safae Ghay','Naima Saghrioui','Sara Winter','Jaylisa Emanuelson','Reshma Ramroop','Sharita Jaipal'];
let people=[];
const $=id=>document.getElementById(id), m=s=>{let [h,mi]=String(s).split(':').map(Number);return h*60+mi}, f=x=>String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');
async function api(path,opts={}){opts.headers=Object.assign({'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json'},opts.headers||{});let r=await fetch(SB+'/rest/v1/'+path,opts);if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function week(){return DAYS.map((_,i)=>({work:i<5,start:'08:00',end:'18:00'}))}
function profile(name,id=null){return {id,name,type:'KCC',active:true,pref:'',week:week(),open:false}}
function today(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('date').value=d.toISOString().slice(0,10)}
function day(){let v=$('date').value;return v?new Date(v+'T12:00:00').getDay()||7:(new Date().getDay()||7)}
function roster(p){let w=p.week[(day()+6)%7];return w&&w.work?w:null}
function hours(w){return(m(w.end)-m(w.start))/60}
function rights(w){let h=hours(w);return h>6?['mini1','big','mini2']:h>4?['mini1','mini2']:[]}
function active(){return people.filter(p=>p.active&&p.type==='KCC'&&roster(p))}
async function load(){let rows=await api('kcc_work_profiles?select=*&order=name');if(!rows.length){await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(NAMES.map(name=>({name})))});rows=await api('kcc_work_profiles?select=*&order=name')}
let ids=rows.map(r=>r.id);let sched=ids.length?await api('kcc_work_schedule?select=*&profile_id=in.('+ids.join(',')+')'):[];people=rows.map(r=>{let p={id:r.id,name:r.name,type:r.type,active:r.active,pref:r.big_break_preference?String(r.big_break_preference).slice(0,5):'',week:week(),open:false};sched.filter(s=>s.profile_id===r.id).forEach(s=>{p.week[s.weekday-1]={work:s.working,start:s.start_time?String(s.start_time).slice(0,5):'08:00',end:s.end_time?String(s.end_time).slice(0,5):'18:00'}});return p});render();generate()}
let saveTimer={};async function saveProfile(p){clearTimeout(saveTimer[p.id]);saveTimer[p.id]=setTimeout(async()=>{try{await api('kcc_work_profiles?id=eq.'+p.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:p.name,type:p.type,active:p.active,big_break_preference:p.pref||null,updated_at:new Date().toISOString()})});await api('kcc_work_schedule?profile_id=eq.'+p.id,{method:'DELETE'});let rows=p.week.map((w,i)=>({profile_id:p.id,weekday:i+1,working:w.work,start_time:w.work?w.start:null,end_time:w.work?w.end:null}));await api('kcc_work_schedule',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows)})}catch(e){console.error(e);alert('Opslaan naar de centrale database is mislukt.')}} ,250)}
async function reset(){if(!confirm('Alle profielen terugzetten naar de basislijst?'))return;await api('kcc_work_schedule',{method:'DELETE'});await api('kcc_work_profiles',{method:'DELETE'});await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(NAMES.map(name=>({name})))});await load()}
function render(){let b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>{let opts='<option value="">Geen voorkeur</option>'+BIG.map(x=>`<option value="${x}" ${p.pref===x?'selected':''}>${x}</option>`).join('');b.insertAdjacentHTML('beforeend',`<tr><td><input class="name" data-i="${i}" value="${p.name}"></td><td><select class="type" data-i="${i}"><option ${p.type==='KCC'?'selected':''}>KCC</option><option ${p.type==='Webcare'?'selected':''}>Webcare</option><option ${p.type==='Coördinator'?'selected':''}>Coördinator</option></select></td><td><select class="pref" data-i="${i}">${opts}</select></td><td><input type="checkbox" class="active" data-i="${i}" ${p.active?'checked':''}></td><td><button class="secondary profileBtn" data-i="${i}">${p.open?'Sluiten':'Profiel'}</button></td><td><button class="secondary remove" data-i="${i}">Verwijder</button></td></tr>`);if(p.open){b.insertAdjacentHTML('beforeend',`<tr class="profileRow"><td colspan="6"><div class="profileBox"><div class="profileTitle"><b>Werkprofiel: ${p.name}</b><span>Opslag: centrale database</span></div><div class="weekGrid">${DAYS.map((d,di)=>{let w=p.week[di];return `<div class="dayCard"><b>${d}</b><label><input type="checkbox" class="dayWork" data-i="${i}" data-d="${di}" ${w.work?'checked':''}> Werkt</label><input type="time" class="dayStart" data-i="${i}" data-d="${di}" value="${w.start}" ${w.work?'':'disabled'}><span>tot</span><input type="time" class="dayEnd" data-i="${i}" data-d="${di}" value="${w.end}" ${w.work?'':'disabled'}></div>`}).join('')}</div></div></td></tr>`)}});b.querySelectorAll('.profileBtn').forEach(x=>x.onclick=()=>{people[+x.dataset.i].open=!people[+x.dataset.i].open;render()});b.querySelectorAll('.remove').forEach(x=>x.onclick=async()=>{let p=people[+x.dataset.i];if(!confirm(p.name+' verwijderen?'))return;await api('kcc_work_profiles?id=eq.'+p.id,{method:'DELETE'});people.splice(+x.dataset.i,1);render();generate()});b.querySelectorAll('input,select').forEach(x=>x.onchange=()=>{let i=+x.dataset.i,d=x.dataset.d,p=people[i];if(x.classList.contains('name'))p.name=x.value;if(x.classList.contains('type'))p.type=x.value;if(x.classList.contains('pref'))p.pref=x.value;if(x.classList.contains('active'))p.active=x.checked;if(d!==undefined){d=+d;if(x.classList.contains('dayWork'))p.week[d].work=x.checked;if(x.classList.contains('dayStart'))p.week[d].start=x.value;if(x.classList.contains('dayEnd'))p.week[d].end=x.value}saveProfile(p);render();generate()});$('statPeople').textContent=active().length}
function overlap(plan,t,kind){let len=kind==='big'?30:10;for(let x=m(t);x<m(t)+len;x+=5){let big=0,total=0;plan.forEach(b=>{let e=m(b.t)+(b.kind==='big'?30:10);if(x>=m(b.t)&&x<e){total++;if(b.kind==='big')big++}});if(kind==='big'&&big>=2)return false;if(kind!=='big'&&total>=3)return false}return true}
function bigLoad(plan,t){let n=0;for(let x=m(t);x<m(t)+30;x+=5)n=Math.max(n,plan.filter(b=>b.kind==='big'&&m(b.t)<=x&&x<m(b.t)+30).length);return n}
function chooseBig(plan,p,w){let valid=BIG.filter(t=>m(t)>=Math.max(720,m(w.start)+60)&&m(t)+30<=m(w.end));if(p.pref&&valid.includes(p.pref))return {t:p.pref,pref:true,exception:false};if(p.pref){valid.sort((a,b)=>Math.abs(m(a)-m(p.pref))-Math.abs(m(b)-m(p.pref)));let t=valid[0];return t?{t,pref:true,exception:false}:null}
let free=valid.find(t=>overlap(plan,t,'big'));if(free)return {t:free,pref:false,exception:false};
let candidates=valid.filter(t=>bigLoad(plan,t)<3);if(!candidates.length)return null;
candidates.sort((a,b)=>bigLoad(plan,a)-bigLoad(plan,b)||m(a)-m(b));let t=candidates[0];return {t,pref:false,exception:true}}
function miniOptions(w,kind,target){let lo=kind==='mini1'?(w.start<='08:30'?600:720):720,hi=kind==='mini1'?(w.start<='08:30'?720:840):1020,a=[];for(let x=lo;x<=hi;x+=5)if(x+10<=m(w.end))a.push(f(x));return a.sort((a,b)=>Math.abs(m(a)-target)-Math.abs(m(b)-target))}
function generate(){let a=active(),plan=[];a.sort((x,y)=>(x.pref?m(x.pref):9999)-(y.pref?m(y.pref):9999));a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('big')){let c=chooseBig(plan,p,w);if(c)plan.push({p,kind:'big',t:c.t,pref:c.pref,exception:c.exception})}});a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('mini1')){let b=plan.find(x=>x.p===p&&x.kind==='big'),o=miniOptions(w,'mini1',b?m(b.t)-120:m(w.start)+120),t=o.find(z=>overlap(plan,z,'mini1'));if(t)plan.push({p,kind:'mini1',t,pref:false})}});a.forEach(p=>{let w=roster(p),r=rights(w);if(r.includes('mini2')){let b=plan.find(x=>x.p===p&&x.kind==='big'),f1=plan.find(x=>x.p===p&&x.kind==='mini1'),target=b?m(b.t)+120:f1?m(f1.t)+120:m(w.start)+240,o=miniOptions(w,'mini2',target),t=o.find(z=>overlap(plan,z,'mini2'));if(t)plan.push({p,kind:'mini2',t,pref:false})}});renderPlan(plan);score(plan,a)}
function score(plan,a){let hard=0,exceptions=0,missing=0;for(let t=720;t<=990;t+=5){let bs=plan.filter(b=>m(b.t)<=t&&t<m(b.t)+(b.kind==='big'?30:10));let big=bs.filter(b=>b.kind==='big');if(big.some(b=>b.pref))continue;if(big.length>2)hard++;if(bs.length>3)hard++}a.forEach(p=>{let w=roster(p),r=rights(w);r.forEach(k=>{if(!plan.some(b=>b.p===p&&b.kind===k))missing++})});exceptions=plan.filter(b=>b.exception).length;let penalty=hard+exceptions+missing;$('score').textContent=penalty?Math.max(0,100-penalty*3)+'%':'100%';$('statWarnings').textContent=hard+exceptions+missing;$('statBreaks').textContent=plan.length;$('alerts').innerHTML=(hard||exceptions||missing)?`<div class="alert">⚠️ ${hard+exceptions+missing} aandachtspunt(en). ${missing?missing+' pauzes konden niet binnen de harde capaciteit worden ingepland. ':''}${exceptions?exceptions+' grote pauzes gebruiken een uitzonderingsplek (max. 3 tegelijk). ':''}Persoonlijke voorkeuren overrulen de bezettingsregels en tellen niet mee als bezettingsverlies.</div>`:'<div class="alert">✓ Geen aandachtspunten. Alle pauzes passen binnen de regels.</div>'}
function renderPlan(plan){let s=$('schedule');s.innerHTML='';let by={};plan.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>m(a)-m(b)).forEach(t=>{s.insertAdjacentHTML('beforeend',`<div class="slot"><time>${t}</time><div class="cards">${by[t].map(b=>`<div class="breakcard ${b.kind==='big'?'bigcard':''} ${b.exception?'warningcard':''}"><b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'}${b.exception?' ⚠️':''}<input type="time" value="${b.t}"></div>`).join('')}</div></div>`)});s.querySelectorAll('input').forEach((x,i)=>x.onchange=()=>{let b=plan[i];if(b){b.t=x.value;renderPlan(plan);score(plan,active())}})}
async function init(){today();$('loadDemo').onclick=reset;$('generate').onclick=generate;$('addPerson').onclick=async()=>{let r=await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:'Nieuwe collega'})});let p=profile(r[0].name,r[0].id);p.id=r[0].id;people.push(p);await saveProfile(p);render();generate()};$('date').onchange=generate;try{await load()}catch(e){console.error(e);$('peopleBody').innerHTML='<tr><td colspan="6">Kan de centrale database niet laden.</td></tr>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();