(()=>{'use strict';
const SB='https://lfyxjbcsrsmbaflhbtbx.supabase.co',KEY='sb_publishable_VrglfWR4mfvAcrm1MLZY3Q_XH6L5st1';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'],BIG=['12:00','12:35','13:10','13:45','14:20','14:55','15:30','16:00'];let people=[],$=x=>document.getElementById(x),M=x=>{let[a,b]=String(x).split(':').map(Number);return a*60+b},F=x=>String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');
async function api(path,o={}){o.headers={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(o.headers||{})};let r=await fetch(SB+'/rest/v1/'+path,o),t=await r.text();if(!r.ok)throw Error(t||r.status);return t.trim()?JSON.parse(t):null}
function wk(){return DAYS.map((_,i)=>({work:i<5,start:'08:00',end:'18:00'}))}function today(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('date').value=d.toISOString().slice(0,10)}function dow(){return(new Date($('date').value+'T12:00')).getDay()||7}function ro(p){return p.week[dow()-1]}function hrs(w){return(M(w.end)-M(w.start))/60}function rights(w){return hrs(w)>6?['mini1','big','mini2']:hrs(w)>4?['mini1','mini2']:[]}function active(){return people.filter(p=>p.active&&p.type==='KCC'&&ro(p)?.work)}
async function load(){let rows=await api('kcc_work_profiles?select=*&order=name'),ids=(rows||[]).map(x=>x.id),ss=ids.length?await api('kcc_work_schedule?select=*&profile_id=in.('+ids.join(',')+')'):[];people=(rows||[]).map(r=>{let p={id:r.id,name:r.name,type:r.type||'KCC',active:r.active!==false,pref:r.big_break_preference?String(r.big_break_preference).slice(0,5):'',week:wk(),open:false};(ss||[]).filter(s=>s.profile_id===r.id).forEach(s=>p.week[s.weekday-1]={work:s.working,start:s.start_time?String(s.start_time).slice(0,5):'08:00',end:s.end_time?String(s.end_time).slice(0,5):'18:00'});return p});render();generate()}
function overlap(plan,t,kind,ignorePref=true){let s=M(t),e=s+(kind==='big'?30:10);return Math.max(...Array.from({length:Math.max(1,(e-s)/5)},(_,i)=>{let x=s+i*5;return plan.filter(b=>(ignorePref||!b.pref)&&M(b.t)<=x&&x<M(b.t)+(b.kind==='big'?30:10)).length}),0)}
function bigSlots(w){return BIG.filter(t=>M(t)>=Math.max(720,M(w.start))&&M(t)+30<=M(w.end))}
function chooseBig(plan,p,w){let slots=bigSlots(w);if(!slots.length)return null;if(p.pref&&slots.includes(p.pref))return{t:p.pref,pref:true,exception:false};let free=slots.filter(t=>overlap(plan,t,'big')<2);if(free.length)return{t:free[0],pref:false,exception:false};let ex=slots.filter(t=>overlap(plan,t,'big')<3).sort((a,b)=>overlap(plan,a,'big')-overlap(plan,b,'big')||M(a)-M(b));return ex.length?{t:ex[0],pref:false,exception:true}:null}
function miniRange(w,k){let early=M(w.start)<=510;let lo=k==='mini1'?(early?600:720):720,hi=k==='mini1'?(early?720:840):1020;let out=[];for(let x=lo;x<=hi&&x+10<=M(w.end);x+=5)out.push(F(x));return out}
function assignMini(plan,p,w,k,big,first){let target=big?(k==='mini1'?M(big.t)-120:M(big.t)+120):(M(w.start)+(first?120:240));let c=miniRange(w,k).map(t=>({t,load:overlap(plan,t,'mini'),dist:Math.abs(M(t)-target)})).filter(x=>x.load<3).sort((a,b)=>a.dist-b.dist||a.load-b.load||M(a.t)-M(b.t));return c[0]?.t||null}
function generate(){let a=active().sort((x,y)=>M(ro(x).start)-M(ro(y).start)||x.name.localeCompare(y.name)),plan=[];
// Grote pauze: eerst persoonlijke voorkeuren, daarna vroege starters. Max 2 normaal; derde is expliciete uitzondering.
a.filter(p=>p.pref).forEach(p=>{let c=chooseBig(plan,p,ro(p));if(c)plan.push({p,kind:'big',t:c.t,pref:true,exception:false})});a.filter(p=>!p.pref).forEach(p=>{let c=chooseBig(plan,p,ro(p));if(c)plan.push({p,kind:'big',t:c.t,pref:false,exception:c.exception})});
// Mini 1/2 worden daarna verdeeld op laagste actuele belasting, niet persoon-voor-persoon.
for(let pass of ['mini1','mini2']){let candidates=a.filter(p=>rights(ro(p)).includes(pass)).sort((x,y)=>M(ro(x).start)-M(ro(y).start));for(let p of candidates){let w=ro(p),b=plan.find(x=>x.p===p&&x.kind==='big'),f=plan.find(x=>x.p===p&&x.kind==='mini1'),t=assignMini(plan,p,w,pass,b,f);if(t)plan.push({p,kind:pass,t,pref:false})}}
plan.sort((a,b)=>M(a.t)-M(b.t)||a.kind.localeCompare(b.kind));renderPlan(plan);score(plan,a)}
function score(plan,a){let missing=0; a.forEach(p=>rights(ro(p)).forEach(k=>{if(!plan.some(b=>b.p===p&&b.kind===k))missing++}));let exceptions=plan.filter(b=>b.exception&&!b.pref).length;let warnings=missing+exceptions;let score=missing?Math.max(0,100-missing*4-exceptions*1):Math.max(0,100-exceptions*1);$('statWarnings').textContent=warnings;$('statBreaks').textContent=plan.length;$('score').textContent=score+'%';$('alerts').innerHTML=warnings?`<div class=alert>⚠️ ${warnings} aandachtspunt(en). ${missing?missing+' pauze(s) konden niet worden geplaatst. ':''}${exceptions?exceptions+' grote pauze(s) gebruiken de toegestane uitzonderingsplek (3 tegelijk). ':''}Persoonlijke voorkeuren zijn volledig vrijgesteld.</div>`:'<div class=alert>✓ Alle pauzes zijn geplaatst binnen de normale regels.</div>'}
function renderPlan(plan){let s=$('schedule');s.innerHTML='';let by={};plan.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>M(a)-M(b)).forEach(t=>s.insertAdjacentHTML('beforeend',`<div class=slot><time>${t}</time><div class=cards>${by[t].map(b=>`<div class="breakcard ${b.kind==='big'?'bigcard':''} ${b.exception?'warningcard':''}"><b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'}${b.exception?' ⚠️':''}</div>`).join('')}</div></div>`))}
function render(){let b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>b.insertAdjacentHTML('beforeend',`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.pref||'Geen voorkeur'}</td><td>${p.active?'✓':'—'}</td><td><button class=profileBtn data-i=${i}>Profiel</button></td></tr>`));b.querySelectorAll('.profileBtn').forEach(x=>x.onclick=()=>{alert('Werkprofiel blijft centraal opgeslagen. Open de huidige profielbewerking via de eerdere V2-interface.');})}async function init(){today();$('generate').onclick=generate;await load()}init()})();