(()=>{
'use strict';
const SB='https://lfyxjbcsrsmbaflhbtbx.supabase.co';
const KEY='sb_publishable_VrglfWR4mfvAcrm1MLZY3Q_XH6L5st1';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'];
const BIG=['12:00','12:35','13:10','13:45','14:20','14:55','15:30','16:00'];
const NAMES=['Harman Satpal','Peggy Peerkhan','Nella Faneyte','Hester van den Wittenboer','Marie-Jean Djaoen','Simone de Groot','Anoushka Ramcharan','David van Onselen','Alicia Rodriques','Chelsea Hibbert','Turgay Can','Melvin Cairo','Magdalena de Windt','Gernarda Raap','Hriteesha Poeran','Sjaiesta Billar','Tamara Kuntkes','Mathijs Van der Wouden','Dharendenie Autar','Fara Wirjopawiro Durga','Cherrelle Goudmijn','Asli Semen','Cindy Wooter','Smahane Almakroudi','Savienne Wawoe','Dries Mouna','Mandy Spaans','Shanaaz Nasrullah','Safae Ghay','Naima Saghrioui','Sara Winter','Jaylisa Emanuelson','Reshma Ramroop','Sharita Jaipal'];
let people=[]; const $=id=>document.getElementById(id); const m=s=>{let [h,mi]=String(s).split(':').map(Number);return h*60+mi}; const f=x=>String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0');
async function api(path,opts={}){opts.headers=Object.assign({'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json'},opts.headers||{});let r=await fetch(SB+'/rest/v1/'+path,opts),text=await r.text();if(!r.ok)throw new Error(text||('HTTP '+r.status));if(!text.trim())return null;try{return JSON.parse(text)}catch(e){throw new Error('Ongeldige database-respons: '+text.slice(0,200))}}
function week(){return DAYS.map((_,i)=>({work:i<5,start:'08:00',end:'18:00'}))}
function today(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());if($('date'))$('date').value=d.toISOString().slice(0,10)}
function day(){let v=$('date')?.value;return v?(new Date(v+'T12:00:00').getDay()||7):(new Date().getDay()||7)}
function roster(p){let w=p.week[(day()+6)%7];return w&&w.work?w:null}
function hours(w){return(m(w.end)-m(w.start))/60}
function rights(w){let h=hours(w);return h>6?['mini1','big','mini2']:h>4?['mini1','mini2']:[]}
function active(){return people.filter(p=>p.active&&p.type==='KCC'&&roster(p))}
function profile(name,id=null){return{id,name,type:'KCC',active:true,pref:'',week:week(),open:false}}
async function load(){let rows=await api('kcc_work_profiles?select=*&order=name');if(!rows||!rows.length){await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(NAMES.map(name=>({name,type:'KCC',active:true})))});rows=await api('kcc_work_profiles?select=*&order=name')};let ids=rows.map(r=>r.id);let sched=ids.length?await api('kcc_work_schedule?select=*&profile_id=in.('+ids.join(',')+')'):[];people=rows.map(r=>{let p={id:r.id,name:r.name,type:r.type||'KCC',active:r.active!==false,pref:r.big_break_preference?String(r.big_break_preference).slice(0,5):'',week:week(),open:false};(sched||[]).filter(s=>s.profile_id===r.id).forEach(s=>p.week[s.weekday-1]={work:s.working,start:s.start_time?String(s.start_time).slice(0,5):'08:00',end:s.end_time?String(s.end_time).slice(0,5):'18:00'});return p});render();generate()}
let saveTimer={};async function saveProfile(p){clearTimeout(saveTimer[p.id]);saveTimer[p.id]=setTimeout(async()=>{try{await api('kcc_work_profiles?id=eq.'+p.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:p.name,type:p.type,active:p.active,big_break_preference:p.pref||null,updated_at:new Date().toISOString()})});let rows=p.week.map((w,i)=>({profile_id:p.id,weekday:i+1,working:w.work,start_time:w.work?w.start:null,end_time:w.work?w.end:null}));await api('kcc_work_schedule?on_conflict=profile_id%2Cweekday',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)})}catch(e){console.error(e);alert('Opslaan naar de centrale database is mislukt: '+e.message)}},350)}
async function reset(){if(!confirm('Alle profielen terugzetten naar de basislijst?'))return;await api('kcc_work_schedule',{method:'DELETE'});await api('kcc_work_profiles',{method:'DELETE'});await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(NAMES.map(name=>({name,type:'KCC',active:true})))});await load()}
function render(){let b=$('peopleBody');if(!b)return;b.innerHTML='';people.forEach((p,i)=>{let opts='<option value="">Geen voorkeur</option>'+BIG.map(x=>`<option value="${x}" ${p.pref===x?'selected':''}>${x}</option>`).join('');b.insertAdjacentHTML('beforeend',`<tr><td><input class="name" data-i="${i}" value="${p.name}"></td><td><select class="type" data-i="${i}"><option ${p.type==='KCC'?'selected':''}>KCC</option><option ${p.type==='Webcare'?'selected':''}>Webcare</option><option ${p.type==='Coördinator'?'selected':''}>Coördinator</option></select></td><td><select class="pref" data-i="${i}">${opts}</select></td><td><input type="checkbox" class="active" data-i="${i}" ${p.active?'checked':''}></td><td><button class="secondary profileBtn" data-i="${i}">${p.open?'Sluiten':'Profiel'}</button></td><td><button class="secondary remove" data-i="${i}">Verwijder</button></td></tr>`);if(p.open)b.insertAdjacentHTML('beforeend',`<tr class="profileRow"><td colspan="6"><div class="profileBox"><div class="profileTitle"><b>Werkprofiel: ${p.name}</b><span>Opslag: centrale database</span></div><div class="weekGrid">${DAYS.map((d,di)=>{let w=p.week[di];return `<div class="dayCard"><b>${d}</b><label><input type="checkbox" class="dayWork" data-i="${i}" data-d="${di}" ${w.work?'checked':''}> Werkt</label><input type="time" class="dayStart" data-i="${i}" data-d="${di}" value="${w.start}" ${w.work?'':'disabled'}><span>tot</span><input type="time" class="dayEnd" data-i="${i}" data-d="${di}" value="${w.end}" ${w.work?'':'disabled'}></div>`}).join('')}</div></div></td></tr>`)});b.querySelectorAll('.profileBtn').forEach(x=>x.onclick=()=>{people[+x.dataset.i].open=!people[+x.dataset.i].open;render()});b.querySelectorAll('.remove').forEach(x=>x.onclick=async()=>{let p=people[+x.dataset.i];if(!confirm(p.name+' verwijderen?'))return;await api('kcc_work_profiles?id=eq.'+p.id,{method:'DELETE'});people.splice(+x.dataset.i,1);render();generate()});b.querySelectorAll('input,select').forEach(x=>x.onchange=()=>{let i=+x.dataset.i,d=x.dataset.d,p=people[i];if(x.classList.contains('name'))p.name=x.value;if(x.classList.contains('type'))p.type=x.value;if(x.classList.contains('pref'))p.pref=x.value;if(x.classList.contains('active'))p.active=x.checked;if(d!==undefined){d=+d;if(x.classList.contains('dayWork'))p.week[d].work=x.checked;if(x.classList.contains('dayStart'))p.week[d].start=x.value;if(x.classList.contains('dayEnd'))p.week[d].end=x.value}saveProfile(p);render();generate()});if($('statPeople'))$('statPeople').textContent=active().length}
function overlap(plan,t,kind){let len=kind==='big'?30:10;for(let x=m(t);x<m(t)+len;x+=5){let total=0,big=0;plan.forEach(b=>{let e=m(b.t)+(b.kind==='big'?30:10);if(x>=m(b.t)&&x<e){total++;if(b.kind==='big'&&!b.pref)big++}});if(kind==='big'&&!plan.some(b=>b.kind==='big'&&b.pref&&m(b.t)<=x&&x<m(b.t)+30)&&big>=2)return false;if(kind!=='big'&&total>=3)return false}return true}
function validBig(p,w){return BIG.filter(t=>m(t)>=Math.max(720,m(w.start)+60)&&m(t)+30<=m(w.end))}
function chooseBig(plan,p,w){let valid=validBig(p,w);if(!valid.length)return null;if(p.pref&&valid.includes(p.pref))return{t:p.pref,pref:true,exception:false};if(p.pref){valid.sort((a,b)=>Math.abs(m(a)-m(p.pref))-Math.abs(m(b)-m(p.pref)));return{t:valid[0],pref:true,exception:false}}
let free=valid.filter(t=>overlap(plan,t,'big'));if(free.length){free.sort((a,b)=>{let la=plan.filter(x=>x.kind==='big'&&!x.pref&&m(x.t)===m(a)).length,lb=plan.filter(x=>x.kind==='big'&&!x.pref&&m(x.t)===m(b)).length;return la-lb||m(a)-m(b)});return{t:free[0],pref:false,exception:false}}
let ex=valid.filter(t=>{let n=plan.filter(x=>x.kind==='big'&&!x.pref&&m(x.t)===m(t)).length;return n<3});if(!ex.length)return null;ex.sort((a,b)=>m(a)-m(b));return{t:ex[0],pref:false,exception:true}}
function miniOptions(w,kind,target){let lo=kind==='mini1'?(w.start<='08:30'?600:720):720,hi=kind==='mini1'?(w.start<='08:30'?720:840):1020,a=[];for(let x=lo;x<=hi;x+=5)if(x+10<=m(w.end))a.push(f(x));return a.sort((a,b)=>Math.abs(m(a)-target)-Math.abs(m(b)-target))}
function generate(){let a=active().slice().sort((x,y)=>m(roster(x).start)-m(roster(y).start)||((x.pref?0:1)-(y.pref?0:1))||x.name.localeCompare(y.name));let plan=[];
// Grote pauzes: persoonlijke voorkeur eerst en volledig vrijgesteld van capaciteit/score.
a.filter(p=>p.pref).forEach(p=>{let c=chooseBig(plan,p,roster(p));if(c)plan.push({p,kind:'big',t:c.t,pref:true,exception:false})});
// Daarna normale pauzes op starttijd: vroege starters krijgen de vroegste vrije groepen.
a.filter(p=>!p.pref).forEach(p=>{let c=chooseBig(plan,p,roster(p));if(c)plan.push({p,kind:'big',t:c.t,pref:false,exception:c.exception})});
// Mini 1 zo dicht mogelijk vóór de grote pauze, met de starttijdvensters als harde rand.
a.forEach(p=>{let w=roster(p),r=rights(w);if(!r.includes('mini1'))return;let b=plan.find(x=>x.p===p&&x.kind==='big'),target=b?m(b.t)-120:m(w.start)+120,o=miniOptions(w,'mini1',target),t=o.find(z=>overlap(plan,z,'mini1'));if(t)plan.push({p,kind:'mini1',t,pref:false})});
// Mini 2 ongeveer 2 uur na mini 1 / grote pauze.
a.forEach(p=>{let w=roster(p),r=rights(w);if(!r.includes('mini2'))return;let b=plan.find(x=>x.p===p&&x.kind==='big'),f1=plan.find(x=>x.p===p&&x.kind==='mini1'),target=b?m(b.t)+120:f1?m(f1.t)+120:m(w.start)+240,o=miniOptions(w,'mini2',target),t=o.find(z=>overlap(plan,z,'mini2'));if(t)plan.push({p,kind:'mini2',t,pref:false})});
plan.sort((a,b)=>m(a.t)-m(b.t)||a.p.name.localeCompare(b.p.name));renderPlan(plan);score(plan,a)}
function score(plan,a){let hard=0,missing=0,exception=0;
// Meet alleen normale bezetting; voorkeuren worden bewust volledig genegeerd.
for(let t=720;t<=1020;t+=5){let bs=plan.filter(b=>!b.pref&&m(b.t)<=t&&t<m(b.t)+(b.kind==='big'?30:10));let big=bs.filter(b=>b.kind==='big');if(big.length>2)hard++;if(bs.length>3)hard++}
a.forEach(p=>rights(roster(p)).forEach(k=>{if(!plan.some(b=>b.p===p&&b.kind===k))missing++}));exception=plan.filter(b=>b.exception&&!b.pref).length;
// Eén overtreding per uniek tijdsblok, niet per minuut. Dit voorkomt extreme straf voor één overlap.
let blocks=new Set();for(let t=720;t<=1020;t+=5){let bs=plan.filter(b=>!b.pref&&m(b.t)<=t&&t<m(b.t)+(b.kind==='big'?30:10));if(bs.filter(b=>b.kind==='big').length>2||bs.length>3)blocks.add(Math.floor(t/5))}hard=blocks.size;
let penalty=hard*2+exception+missing*2;$('score').textContent=penalty?Math.max(0,100-penalty*2)+'%':'100%';$('statWarnings').textContent=hard+exception+missing;$('statBreaks').textContent=plan.length;
$('alerts').innerHTML=(hard||exception||missing)?`<div class="alert">⚠️ ${hard+exception+missing} aandachtspunt(en). ${missing?missing+' pauzes konden niet worden ingepland. ':''}${exception?exception+' normale grote pauze(s) gebruiken een uitzonderingsplek. ':''}Persoonlijke voorkeuren zijn volledig vrijgesteld van de bezettingsscore.</div>`:'<div class="alert">✓ Geen aandachtspunten. Alle pauzes passen binnen de regels.</div>'}
function renderPlan(plan){let s=$('schedule');if(!s)return;s.innerHTML='';let by={};plan.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>m(a)-m(b)).forEach(t=>{s.insertAdjacentHTML('beforeend',`<div class="slot"><time>${t}</time><div class="cards">${by[t].map(b=>`<div class="breakcard ${b.kind==='big'?'bigcard':''} ${b.exception?'warningcard':''}"><b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'}${b.exception?' ⚠️':''}<input type="time" value="${b.t}"></div>`).join('')}</div></div>`)});s.querySelectorAll('input').forEach((x,i)=>x.onchange=()=>{let flat=plan.slice().sort((a,b)=>m(a.t)-m(b.t)||a.p.name.localeCompare(b.p.name)),b=flat[i];if(b){b.t=x.value;renderPlan(plan);score(plan,active())}})}
async function init(){today();if($('loadDemo'))$('loadDemo').onclick=reset;if($('generate'))$('generate').onclick=generate;if($('addPerson'))$('addPerson').onclick=async()=>{let r=await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:'Nieuwe collega',type:'KCC',active:true})});let p=profile(r[0].name,r[0].id);people.push(p);await saveProfile(p);render();generate()};if($('date'))$('date').onchange=generate;try{await load()}catch(e){console.error(e);if($('peopleBody'))$('peopleBody').innerHTML='<tr><td colspan="6">Kan de centrale database niet laden.</td></tr>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();