const people=[];const $=id=>document.getElementById(id);
const demoStarts=['08:00','08:00','08:00','08:00','08:00','08:30','08:30','08:30','08:30','08:30','09:00','09:00','09:00','09:00','09:30','09:30','09:30','09:30'];
const slots=[];for(let m=600;m<=1020;m+=5)slots.push(`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`);
function mins(s){const [h,m]=s.split(':').map(Number);return h*60+m}
function demo(){people.length=0;demoStarts.forEach((start,i)=>people.push({id:crypto.randomUUID(),name:`Collega ${String(i+1).padStart(2,'0')}`,start,end:'16:30',type:'KCC',pref:''}));people[5].end='17:00';people[9].end='17:00';people[10].end='17:30';people[11].end='17:30';people[12].end='17:30';people.slice(14).forEach(p=>p.end='14:30');renderPeople();generate()}
function renderPeople(){const b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><input type=text value="${p.name}" data-i="${i}" class="name"></td><td><select class=start data-i="${i}">${['08:00','08:30','09:00','09:30'].map(x=>`<option ${x===p.start?'selected':''}>${x}</option>`).join('')}</select></td><td><input type=time value="${p.end}" data-i="${i}" class=end></td><td><select class=type data-i="${i}"><option ${p.type==='KCC'?'selected':''}>KCC</option><option ${p.type==='Webcare'?'selected':''}>Webcare</option><option ${p.type==='Coördinator'?'selected':''}>Coördinator</option></select></td><td><select class=pref data-i="${i}"><option value="" ${!p.pref?'selected':''}>Geen voorkeur</option>${['10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00'].map(x=>`<option ${x===p.pref?'selected':''}>${x}</option>`).join('')}</select></td><td><button class=remove data-i="${i}">Verwijder</button></td>`;b.appendChild(tr)});document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('change',e=>{const i=+e.target.dataset.i;if(e.target.classList.contains('name'))people[i].name=e.target.value;if(e.target.classList.contains('start'))people[i].start=e.target.value;if(e.target.classList.contains('end'))people[i].end=e.target.value;if(e.target.classList.contains('type'))people[i].type=e.target.value;if(e.target.classList.contains('pref'))people[i].pref=e.target.value;generate()})});document.querySelectorAll('.remove').forEach(x=>x.onclick=()=>{people.splice(+x.dataset.i,1);renderPeople();generate()});$('statPeople').textContent=people.filter(p=>p.type==='KCC').length}
function eligible(p){const hours=(mins(p.end)-mins(p.start))/60;return hours>4&&hours<=6?['mini1','mini2']:hours>6?['mini1','big','mini2']:[]}
function windowFor(p,kind){if(kind==='mini1')return p.start<='08:30'?[600,720]:[720,840];if(kind==='big')return [720,960];return [720,1020]}
function overlaps(bs,p,t,kind){const a=mins(t),duration=kind==='big'?30:10;return bs.some(b=>{if(b.p===p)return false;const b0=mins(b.t),b1=b0+(b.kind==='big'?30:10),a1=a+duration;return a<b1&&a1>b0})}
function samePersonTooClose(bs,p,t){const a=mins(t);return bs.filter(b=>b.p===p).some(b=>Math.abs(a-mins(b.t))<105)}
function generate(){const active=people.filter(p=>p.type==='KCC');const bs=[];const ordered=[...active].sort((a,b)=>a.start.localeCompare(b.start));
for(const kind of ['mini1','big','mini2']){for(const p of ordered){if(!eligible(p).includes(kind))continue;let [lo,hi]=windowFor(p,kind);let opts=slots.filter(t=>mins(t)>=lo&&mins(t)<=hi&&mins(t)>=mins(p.start)+10&&mins(t)<mins(p.end));if(p.pref)opts.sort((a,b)=>Math.abs(mins(a)-mins(p.pref))-Math.abs(mins(b)-mins(p.pref)));
opts.sort((a,b)=>{const ca=capacityPenalty(bs,a,kind),cb=capacityPenalty(bs,b,kind);const ideal=kind==='mini1'?mins(p.start)+120:kind==='big'?mins(p.start)+300:mins(p.start)+420;return ca-cb||Math.abs(mins(a)-ideal)-Math.abs(mins(b)-ideal)});
let chosen=opts.find(t=>!samePersonTooClose(bs,p,t)&&!overlaps(bs,p,t,kind)&&capacityPenalty(bs,t,kind)===0);if(!chosen)chosen=opts.find(t=>!samePersonTooClose(bs,p,t)&&capacityPenalty(bs,t,kind)<=1)||opts[0];if(chosen)bs.push({p,kind,t:chosen});}}
renderSchedule(bs);score(bs,active)}
function capacityPenalty(bs,t,kind){const a=mins(t),d=kind==='big'?30:10;let penalty=0;for(let m=a;m<a+d;m+=5){const big=bs.filter(b=>b.kind==='big'&&m>=mins(b.t)&&m<mins(b.t)+30).length;const mini=bs.filter(b=>b.kind!=='big'&&m>=mins(b.t)&&m<mins(b.t)+10).length;if(kind==='big'&&big>=2)penalty+=2;if(kind!=='big'&&big>=2&&mini>=1)penalty+=2;if(kind!=='big'&&big<2&&mini>=2)penalty+=1}return penalty}
function score(bs,active){let violations=0,soft=0;const allTimes=[...new Set(bs.map(b=>b.t))];allTimes.forEach(t=>{const big=bs.filter(b=>b.kind==='big'&&mins(t)>=mins(b.t)&&mins(t)<mins(b.t)+30).length;const mini=bs.filter(b=>b.kind!=='big'&&mins(t)>=mins(b.t)&&mins(t)<mins(b.t)+10).length;if(big>2||mini>1&&big>=2)violations++});bs.forEach(b=>{const mine=bs.filter(x=>x.p===b.p&&x!==b);mine.forEach(x=>{const gap=Math.abs(mins(x.t)-mins(b.t));if(gap<90)violations++;if(gap<105)soft++})});const score=Math.max(0,100-violations*10-soft*2);$('score').textContent=`${score}%`;$('statWarnings').textContent=violations;$('statBreaks').textContent=bs.length;$('alerts').innerHTML=violations?`<div class=alert>⚠️ ${violations} aandachtspunt(en). De planner toont de best mogelijke verdeling binnen de huidige regels.</div>`:''}
function renderSchedule(bs){const s=$('schedule');s.innerHTML='';const by={};bs.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>mins(a)-mins(b)).forEach(t=>{const slot=document.createElement('div');slot.className='slot';slot.innerHTML=`<time>${t}</time><div class=cards></div>`;const cards=slot.querySelector('.cards');by[t].forEach(b=>{const c=document.createElement('div');c.className=`breakcard ${b.kind==='big'?'bigcard':''}`;c.innerHTML=`<b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'} <input type=time value="${b.t}">`;c.querySelector('input').onchange=e=>{b.t=e.target.value;renderSchedule(bs);score(bs,people.filter(p=>p.type==='KCC'))};cards.appendChild(c)});s.appendChild(slot)})}
$('loadDemo').onclick=demo;$('generate').onclick=generate;$('addPerson').onclick=()=>{people.push({id:crypto.randomUUID(),name:'Nieuwe collega',start:'08:00',end:'16:30',type:'KCC',pref:''});renderPeople();generate()};$('date').valueAsDate=new Date();demo();