const people=[];const $=id=>document.getElementById(id);const times=['10:00','10:15','10:30','10:45','11:00','11:15','11:30','11:45','12:00','12:15','12:30','12:45','13:00','13:15','13:30','13:45','14:00','14:15','14:30','14:45','15:00','15:15','15:30','15:45'];
function demo(){people.length=0;const starts=['08:00','08:00','08:00','08:00','08:00','08:30','08:30','08:30','08:30','09:00','09:00','09:00','09:00','09:00','09:30','09:30','09:30','09:30','09:30'];starts.forEach((start,i)=>people.push({id:crypto.randomUUID(),name:`Collega ${String(i+1).padStart(2,'0')}`,start,end:'18:00',type:'KCC',pref:''}));renderPeople();generate()}
function renderPeople(){const b=$('peopleBody');b.innerHTML='';people.forEach((p,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><input type=text value="${p.name}" data-i="${i}" class="name"></td><td><select class=start data-i="${i}">${['08:00','08:30','09:00','09:30'].map(x=>`<option ${x===p.start?'selected':''}>${x}</option>`).join('')}</select></td><td><input type=time value="${p.end}" data-i="${i}" class=end></td><td><select class=type data-i="${i}"><option ${p.type==='KCC'?'selected':''}>KCC</option><option ${p.type==='Webcare'?'selected':''}>Webcare</option><option ${p.type==='Coördinator'?'selected':''}>Coördinator</option></select></td><td><select class=pref data-i="${i}"><option value="" ${!p.pref?'selected':''}>Geen voorkeur</option>${['10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00'].map(x=>`<option ${x===p.pref?'selected':''}>${x}</option>`).join('')}</select></td><td><button class=remove data-i="${i}">Verwijder</button></td>`;b.appendChild(tr)});document.querySelectorAll('input,select').forEach(el=>{el.addEventListener('change',e=>{const i=+e.target.dataset.i;if(e.target.classList.contains('name'))people[i].name=e.target.value;if(e.target.classList.contains('start'))people[i].start=e.target.value;if(e.target.classList.contains('end'))people[i].end=e.target.value;if(e.target.classList.contains('type'))people[i].type=e.target.value;if(e.target.classList.contains('pref'))people[i].pref=e.target.value;generate()})});document.querySelectorAll('.remove').forEach(x=>x.onclick=()=>{people.splice(+x.dataset.i,1);renderPeople();generate()});$('statPeople').textContent=people.filter(p=>p.type==='KCC').length}
function mins(s){const [h,m]=s.split(':').map(Number);return h*60+m}function fmt(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function eligible(p){const hours=(mins(p.end)-mins(p.start))/60;return hours>4&&hours<=6?['mini1','mini2']:hours>6?['mini1','big','mini2']:[]}
function slotsFor(p,kind){if(kind==='mini1')return p.start<='08:30'?times.filter(x=>mins(x)>=600&&mins(x)<=720):times.filter(x=>mins(x)>=720&&mins(x)<=840);if(kind==='big')return times.filter(x=>mins(x)>=720&&mins(x)<=960);return times.filter(x=>mins(x)>=720&&mins(x)<=960)}
function generate(){const active=people.filter(p=>p.type==='KCC');const breaks=[];const count={};const add=(p,kind,t)=>{breaks.push({p,kind,t});count[t]=(count[t]||0)+1};const ordered=[...active].sort((a,b)=>(a.start.localeCompare(b.start))||((a.pref?0:1)-(b.pref?0:1)));
for(const kind of ['mini1','big','mini2'])for(const p of ordered){if(!eligible(p).includes(kind))continue;let opts=slotsFor(p,kind);if(p.pref){opts.sort((a,b)=>Math.abs(mins(a)-mins(p.pref))-Math.abs(mins(b)-mins(p.pref)))}opts=opts.sort((a,b)=>(count[a]||0)-(count[b]||0)||Math.abs(mins(a)-(kind==='mini1'?mins(p.start)+120:mins(p.start)+240))-Math.abs(mins(b)-(kind==='mini1'?mins(p.start)+120:mins(p.start)+240)));let chosen=opts.find(t=>{if(kind==='big'&&(count[t]||0)>=2)return false;const mine=breaks.filter(x=>x.p===p).map(x=>mins(x.t));return mine.every(x=>Math.abs(x-mins(t))>=90)});if(!chosen)chosen=opts.find(t=>kind!=='big'||(count[t]||0)<3)||opts[0];add(p,kind,chosen)}
renderSchedule(breaks);score(breaks,active)}
function score(bs,active){let warnings=0;Object.entries(bs.reduce((a,b)=>(a[b.t]=(a[b.t]||[]).concat(b),a),{})).forEach(([t,x])=>{if(x.filter(b=>b.kind==='big').length>2)warnings++});bs.forEach(b=>{const mine=bs.filter(x=>x.p===b.p&&x!==b);mine.forEach(x=>{if(Math.abs(mins(x.t)-mins(b.t))<90)warnings++})});const ideal=active.length*3;const coverage=Math.max(0,100-Math.min(100,warnings*8));$('score').textContent=`${Math.round(coverage)}%`;$('statWarnings').textContent=warnings;$('statBreaks').textContent=bs.length;$('alerts').innerHTML=warnings?`<div class=alert>⚠️ ${warnings} aandachtspunt(en). De planner heeft een best mogelijke verdeling gemaakt.</div>`:''}
function renderSchedule(bs){const s=$('schedule');s.innerHTML='';const by={};bs.forEach(b=>(by[b.t]??=[]).push(b));Object.keys(by).sort((a,b)=>mins(a)-mins(b)).forEach(t=>{const slot=document.createElement('div');slot.className='slot';slot.innerHTML=`<time>${t}</time><div class=cards></div>`;const cards=slot.querySelector('.cards');by[t].forEach(b=>{const c=document.createElement('div');c.className=`breakcard ${b.kind==='big'?'bigcard':''}`;c.innerHTML=`<b>${b.p.name}</b>${b.kind==='big'?'Grote pauze':'Mini'} <input type=time value="${b.t}">`;c.querySelector('input').onchange=e=>{b.t=e.target.value;renderSchedule(bs);score(bs,people.filter(p=>p.type==='KCC'))};cards.appendChild(c)});s.appendChild(slot)})}
$('loadDemo').onclick=demo;$('generate').onclick=generate;$('addPerson').onclick=()=>{people.push({id:crypto.randomUUID(),name:`Nieuwe collega`,start:'08:00',end:'18:00',type:'KCC',pref:''});renderPeople();generate()};$('date').valueAsDate=new Date();demo();