(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  function escapeHtml(str) { return String(str).replace(/[&<>\"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;' }[c])); }
  function msg(text, kind) { $('authMsg').innerHTML = `<div class="alert ${kind}">${escapeHtml(text)}</div>`; }
  function clearMsg() { $('authMsg').innerHTML = ''; }
  function nextUrl() { const params = new URLSearchParams(location.search); return params.get('next') || null; }
  async function afterLogin(session) { let role; try { role = await window.KccAuth.getMyRole(session); } catch (e) { role = null; } if (!role) { msg('Ingelogd, maar dit account is nog niet gekoppeld aan een rol. Vraag de planner om je e-mailadres toe te voegen onder "Toegang & accounts".', 'error'); return; } const target = nextUrl() || window.KccAuth.landingFor(role.role); location.href = target; }
  function setMode(signup) { $('signinForm').style.display = signup ? 'none' : ''; $('signupForm').style.display = signup ? '' : 'none'; $('forgotForm').style.display = 'none'; $('formTitle').textContent = signup ? 'Account aanmaken' : 'Inloggen'; $('formSub').textContent = signup ? 'Alleen mogelijk met een e-mailadres dat de planner heeft toegevoegd.' : 'Log in met het e-mailadres dat de planner voor je heeft toegevoegd.'; $('toggleMode').textContent = signup ? 'Al een account? Inloggen' : 'Nog geen account? Account aanmaken'; clearMsg(); }
  $('toggleMode').onclick = () => setMode($('signupForm').style.display === 'none');
  $('forgotBtn').onclick = () => { $('signinForm').style.display = 'none'; $('signupForm').style.display = 'none'; $('forgotForm').style.display = ''; $('formTitle').textContent = 'Wachtwoord vergeten'; $('formSub').textContent = 'We sturen je een link waarmee je een nieuw wachtwoord kunt instellen.'; clearMsg(); };
  $('signinForm').addEventListener('submit', async (ev) => { ev.preventDefault(); clearMsg(); const btn = ev.target.querySelector('button'); btn.disabled = true; try { const session = await window.KccAuth.signIn($('siEmail').value, $('siPassword').value, $('siRemember').checked); await afterLogin(session); } catch (e) { msg('Inloggen mislukt: ' + e.message, 'error'); } finally { btn.disabled = false; } });
  $('signupForm').addEventListener('submit', async (ev) => { ev.preventDefault(); clearMsg(); if ($('suPassword').value !== $('suPassword2').value) return msg('De wachtwoorden komen niet overeen.', 'error'); const btn = ev.target.querySelector('button'); btn.disabled = true; try { const confirmRedirect = location.origin + location.pathname.replace(/login\.html$/, 'login.html'); const data = await window.KccAuth.signUp($('suEmail').value, $('suPassword').value, confirmRedirect); if (data && data.access_token) { window.KccAuth.saveSession(data, true); await afterLogin(data); } else msg('Account aangemaakt! Check je e-mail om je account te bevestigen. Daarna kom je terug op de inlogpagina.', 'ok'); } catch (e) { msg('Account aanmaken is mislukt: ' + e.message, 'error'); } finally { btn.disabled = false; } });
  $('forgotForm').addEventListener('submit', async (ev) => { ev.preventDefault(); clearMsg(); const btn = ev.target.querySelector('button'); btn.disabled = true; try { const redirect = location.origin + location.pathname.replace(/login\.html$/, 'reset-password.html'); await window.KccAuth.requestPasswordReset($('fpEmail').value, redirect); msg('Als dit e-mailadres bekend is, is er een reset-link verstuurd. Check je inbox (en spam-map).', 'ok'); } catch (e) { msg('Versturen is mislukt: ' + e.message, 'error'); } finally { btn.disabled = false; } });
  (async () => { const session = await window.KccAuth.getSession(); if (session) await afterLogin(session); })();
})();