(()=>{
'use strict';
const SB='https://lfyxjbcsrsmbaflhbtbx.supabase.co';
const KEY='sb_publishable_VrglfWR4mfvAcrm1MLZY3Q_XH6L5st1';
const DAYS=['Ma','Di','Wo','Do','Vr','Za','Zo'];
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
async function api(path,opt={}){const auth=await window.KccAuth.requireSession('planner');if(!auth)throw new Error('Geen geldige plannersessie.');const token=auth.session?.access_token||KEY;const res=await fetch(`${SB}/rest/v1/${path}`,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const text=await res.text();if(!res.ok)throw new Error(text||String(res.status));return text.trim()?JSON.parse(text):null;}
function time(v){if(v==null)return '';let s=String(v).trim();if(!s)return '';if(/^\d{1,2}:\d{2}$/.test(s))return s.padStart(5,'0');if(/^\d{1,2}:\d{2}:\d{2}/.test(s))return s.slice(0,5).padStart(5,'0');return '';}
function normalizeName(s){return String(s??'').trim().toLowerCase().replace(/\s+/g,' ');}
async function readZip(buf){const b=new Uint8Array(buf),dv=new DataView(buf);let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65558);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('Ongeldig Excelbestand: ZIP-structuur ontbreekt.');const cdSize=dv.getUint32(eocd+12,true),cdOff=dv.getUint32(eocd+16,true);let p=cdOff;const files={};while(p<cdOff+cdSize){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),csize=dv.getUint32(p+20,true),nl=dv.getUint16(p+28,true),el=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),off=dv.getUint32(p+42,true);const name=new TextDecoder().decode(b.slice(p+46,p+46+nl));files[name]={method,csize,off};p+=46+nl+el+cl;}async function get(name){const f=files[name];if(!f)return null;const lp=f.off,nl=dv.getUint16(lp+26,true),el=dv.getUint16(lp+28,true),start=lp+30+nl+el,raw=b.slice(start,start+f.csize);if(f.method===0)return raw;if(f.method===8){if(!('DecompressionStream'in window))throw new Error('Deze browser ondersteunt geen Excel-import. Gebruik Edge/Chrome.');const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(ds)).arrayBuffer());}throw new Error('Excel gebruikt een niet-ondersteunde compressiemethode.');}return{get};}
async function parseXlsx(file){const z=await readZip(await file.arrayBuffer()),dec=new TextDecoder(),wb=dec.decode(await z.get('xl/workbook.xml')),rels=dec.decode(await z.get('xl/_rels/workbook.xml.rels'));const rid=(wb.match(/<sheet[^>]*r:id="([^"]+)"/i)||[])[1]||'rId1';let target=(rels.match(new RegExp(`<Relationship[^>]*Id="${rid}"[^>]*Target="([^"]+)"`,'i'))||[])[1]||'worksheets/sheet1.xml';target=target.replace(/^\//,'');if(!target.startsWith('xl/'))target='xl/'+target.replace(/^\.\//,'');const sharedRaw=await z.get('xl/sharedStrings.xml'),shared=[];if(sharedRaw){const sx=new DOMParser().parseFromString(dec.decode(sharedRaw),'application/xml');sx.querySelectorAll('si').forEach(si=>shared.push(Array.from(si.querySelectorAll('t')).map(x=>x.textContent||'').join('')));}const sx=new DOMParser().parseFromString(dec.decode(await z.get(target)),'application/xml'),rows=[];sx.querySelectorAll('sheetData > row').forEach(r=>{const vals=[];r.querySelectorAll(':scope > c').forEach(c=>{const ref=c.getAttribute('r')||'',m=ref.match(/([A-Z]+)\d+$/);let idx=0;if(m){for(const ch of m[1])idx=idx*26+ch.charCodeAt(0)-64;idx--;}while(vals.length<idx)vals.push('');const t=c.getAttribute('t');let v='';if(t==='inlineStr')v=Array.from(c.querySelectorAll('t')).map(x=>x.textContent||'').join('');else if(t==='s')v=shared[Number(c.querySelector('v')?.textContent||0)]||'';else v=c.querySelector('v')?.textContent||'';vals[idx]=v;});rows.push(vals);});return rows;}
async function loadRoster(){const profiles=await api('kcc_work_profiles?select=*&order=name');const ids=profiles.map(p=>p.id);const schedules=ids.length?await api(`kcc_work_schedule?select=*&profile_id=in.(${ids.join(',')})`):[];const by={};(schedules||[]).forEach(s=>{(by[s.profile_id]??={})[s.weekday-1]=s});return profiles.map(p=>({profile:p,week:DAYS.map((_,i)=>{const s=by[p.id]?.[i];return{start:time(s?.start_time),end:time(s?.end_time),working:!!s?.working};})}));}
function exportRoster(){loadRoster().then(data=>{const rows=[['Naam',...DAYS.flatMap(d=>[`${d} start`,`${d} eind`])]];data.forEach(x=>{const r=[x.profile.name];x.week.forEach(w=>r.push(w.working?w.start:'',w.working?w.end:''));rows.push(r);});if(!window.PauzeXlsx)throw new Error('Excel-module ontbreekt.');window.PauzeXlsx.downloadXlsx(rows,'Rooster-alle-collegas.xlsx');}).catch(e=>alert('Exporteren mislukt: '+e.message));}
function parseRows(rows){if(!rows.length)throw new Error('Het Excelbestand bevat geen rijen.');const headers=rows[0].map(v=>String(v??'').trim().toLowerCase()),nameIdx=headers.findIndex(h=>h==='naam'||h==='name'||h==='collega');if(nameIdx<0)throw new Error('Kolom "Naam" ontbreekt.');const map=[];DAYS.forEach((d,i)=>{map[i]=[headers.findIndex(h=>h===`${d.toLowerCase()} start`),headers.findIndex(h=>h===`${d.toLowerCase()} eind`)]});const missing=DAYS.filter((d,i)=>map[i][0]<0||map[i][1]<0);if(missing.length)throw new Error('Ontbrekende kolommen: '+missing.map(d=>`${d} start / ${d} eind`).join(', '));const out=[];rows.slice(1).forEach((r,n)=>{const name=String(r[nameIdx]??'').trim();if(!name)return;const week=map.map(([a,b])=>{const st=time(r[a]),en=time(r[b]);return{start:st,end:en,working:!!(st&&en)}});out.push({row:n+2,name,week});});return out;}
function showPreview(items,current){const byName=new Map(current.map(x=>[normalizeName(x.profile.name),x])),matches=[],newOnes=[],errors=[];items.forEach(it=>{const found=byName.get(normalizeName(it.name));if(found)matches.push({item:it,current:found});else newOnes.push(it);it.week.forEach((w,i)=>{if((w.start&&!w.end)||(!w.start&&w.end))errors.push(`${it.name} — ${DAYS[i]}: start/eind is niet compleet`);});});const modal=document.createElement('div');modal.className='excelModal';modal.innerHTML=`<div class="excelDialog"><h3>Excel-import controleren</h3><p><b>${items.length}</b> collega's gevonden. <b>${matches.length}</b> bestaande profielen worden bijgewerkt en <b>${newOnes.length}</b> nieuwe profielen worden aangemaakt.</p>${errors.length?`<div class="alert error"><b>${errors.length} fout${errors.length>1?'en':''}:</b><br>${errors.slice(0,20).map(esc).join('<br>')}</div>`:'<div class="alert ok">✓ Alle tijden zijn compleet. Lege start- én eindcellen worden als vrije dag opgeslagen.</div>'}<div class="excelPreviewList"><b>Nieuwe profielen:</b> ${newOnes.length?newOnes.map(x=>esc(x.name)).join(', '):'geen'}<br><b>Niet in Excel:</b> ${current.filter(x=>!items.some(i=>normalizeName(i.name)===normalizeName(x.profile.name))).length} bestaande profielen blijven ongewijzigd.<br><b>Type:</b> wordt niet gewijzigd door de import.</div><div class="actions"><button class="secondary excelCancel">Annuleren</button><button class="primary excelApply" ${errors.length?'disabled':''}>Importeren en opslaan</button></div></div>`;document.body.appendChild(modal);modal.querySelector('.excelCancel').onclick=()=>modal.remove();modal.querySelector('.excelApply').onclick=async()=>{const btn=modal.querySelector('.excelApply');btn.disabled=true;btn.textContent='Opslaan...';try{for(const it of items){let target=byName.get(normalizeName(it.name));if(!target){const created=await api('kcc_work_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{name:it.name,type:'KCC',active:true}])});if(!created?.[0]?.id)throw new Error(`Profiel kon niet worden aangemaakt: ${it.name}`);target={profile:created[0]};byName.set(normalizeName(it.name),target);}await api('kcc_work_schedule?on_conflict=profile_id%2Cweekday',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(it.week.map((w,i)=>({profile_id:target.profile.id,weekday:i+1,working:w.working,start_time:w.working?w.start:null,end_time:w.working?w.end:null})))});}modal.remove();alert(`Klaar. ${items.length} collega's verwerkt. Lege tijden zijn als vrije dagen opgeslagen.`);window.location.reload();}catch(e){btn.disabled=false;btn.textContent='Importeren en opslaan';alert('Importeren mislukt: '+e.message)}};}
function importRoster(){const input=document.createElement('input');input.type='file';input.accept='.xlsx';input.onchange=async()=>{if(!input.files[0])return;try{const items=parseRows(await parseXlsx(input.files[0]));showPreview(items,await loadRoster());}catch(e){alert('Excel importeren mislukt: '+e.message)}};input.click();}
function addStyles(){if(document.getElementById('excelRosterStyles'))return;const s=document.createElement('style');s.id='excelRosterStyles';s.textContent='.excelModal{position:fixed;inset:0;background:rgba(15,23,42,.45);display:flex;align-items:center;justify-content:center;z-index:9999;padding:20px}.excelDialog{background:#fff;border-radius:12px;max-width:720px;width:100%;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.2)}.excelDialog h3{margin-top:0}.excelPreviewList{background:#f8fafc;padding:12px;border-radius:8px;margin:12px 0;line-height:1.6}.excelDialog .actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.excelDialog button:disabled{opacity:.5;cursor:not-allowed}';document.head.appendChild(s);}
function init(){addStyles();const imp=$('rosterExcelImport'),exp=$('rosterExcelExport');if(imp){imp.onclick=importRoster;imp.dataset.excelBound='1';}if(exp){exp.onclick=exportRoster;exp.dataset.excelBound='1';}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);setTimeout(init,1500);
})();
